"""add customer_subscriptions table

Revision ID: d73018b05035
Revises: db8dc7402409
Create Date: 2026-07-09 11:07:03.166946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73018b05035'
down_revision: Union[str, Sequence[str], None] = 'db8dc7402409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('milk_type_id', sa.Integer(), nullable=False),
    sa.Column('shift', sa.Enum('MORNING', 'EVENING', name='shift'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['milk_type_id'], ['milk_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'milk_type_id', 'shift', name='uq_customer_milk_type_shift')
    )
    op.create_index(op.f('ix_customer_subscriptions_id'), 'customer_subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_subscriptions_id'), table_name='customer_subscriptions')
    op.drop_table('customer_subscriptions')
    # ### end Alembic commands ###
